openapi: 3.0.0
info:
  description: Basic project with Flask , Connexion and OpenApi 3
  version: 1.0.0
  title: Connexion example
  contact:
    email: kevinmmartins@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
tags:
  - name: alive
    description: Keepalive
paths:
  /ping:
    get:
      tags:
        - alive
      summary: Api keepalive
      description: Api keepalive
      operationId: lingo.controllers.alive_controller.is_alive
      responses:
        "200":
          description: is alive
  /choose/{word_length}:
    get:
      tags: [ Word ]
      operationId: lingo.modules.game_logic.game_logic.choose_random_word
      summary: Get a random word based on word length
      parameters:
        - in: path
          name: word_length
          required: true
          schema:
            type: integer
      responses:
        200:
          description: Return a word
        404:
          description: Can't choose a word

servers:
  - url: http://0.0.0.0:8080/v1/lingo/api